### ISSUE TITLE
indentation issues still

### ISSUE THREAD

**Issue by thujone** [mayabowman/quiz-app#2]
https://github.com/mayabowman/quiz-app/blob/27ff8dda7b12e8e402720afb4a86a36bc43fe0e0/index.html#L29

You can see in this file that the spacing is still off on a lot of these indentations. It could be that VS Code is using both tabs and blank spaces together, and that might be causing the indentation problem. The issue is that a tab in one editor can mean two spaces, while in others it can mean 4 spaces or even 8. There are several settings in VS Code you should check when you have a chance. If you go to Preferences > Settings, you can check to make sure you have these settings: Tab Size = 2; Render Whitespace = 'all'; Insert Spaces = yes

**Comment by mayabowman** [comment]
fixed indentation, and settings in vs code
